### PR TITLE
ctrl+click opens new tab when using Clickable

### PR DESCRIPTION
**Pull request by wllgrnt**
## Motivation and Context
Elsewhere on the web ctrl+click will open whatever you click in a new tab, and for some usecases (e.g. testlooper) this would be useful to have in Cells - this PR adds that functionality.  With thanks to @bokyoungkim-ap for pointers.

## Approach
The changes on line 69 of Clickable.js are sufficient when the onClick function is standard and returning a string. When onClick is more complicated (e.g. check the object, make it if required, then link to it) you need the ctrlClick message.

## How Has This Been Tested?
Ran on testlooper and clicked around + standard unit test battery. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by wllgrnt** [comment]
NB: tests are failing for curl reasons, addressed in  #149

**Comment by atzannes** [comment]
That's great! 
Is it possible to get some unit-testing of this?
Are test failing because of the chrome driver stuff (fixed by PR #149 )?

**Comment by wllgrnt** [comment]
> That's great! Is it possible to get some unit-testing of this? Are test failing because of the chrome driver stuff (fixed by PR #149 )?

Done - added two unit tests and an `object_database_webtest` entry

**Comment by wllgrnt** [comment]
(also version pinned werkzeug as the build was failing due to a deprecation)

**Pull request merged**
