### PR TITLE
Black config & code-base formatting

### PR DESCRIPTION
**Pull request by atzannes**
## Motivation and Context
Good code formatting is important for code readability, but annoying to manually enforce across a team. We use `black` code formatter to automate the task.

## Approach
- Added a pre-commit script to ensure modified files are run through `black`
- Added a `black check` test to TravisCI to prevent regressions
- Updated the `flake8` ignores in `tox.ini` to stop complaining about things that `black` does.
- Reduced `flake8`'s line-length tolerance to 95, the same as black, and manually edited lines that were too long.

## How Has This Been Tested?
TravisCI

### CODE REVIEW

**Comment by atzannes** [comment]
FYI: @dkrasner  @darth-cheney  @braxtonmckee @rubidge  This PR is going in imminently. We formatted our codebase with `black` and installed a pre-commit check and a TravisCI test to keep the code "blacked". Rebase on top of dev as soon as the change is merged to avoid hard rebases in the future.

**Comment by darth-cheney** [comment]
@atzannes Understood

**Comment by atzannes** [comment]
@darth-cheney  @dkrasner @rubidge  merged

**Comment by darth-cheney** [comment]
@atzannes Some weirdness is going on with the `black` formatter (I think). Check out this line:
https://github.com/APrioriInvestments/object_database/blob/dev/object_database/web/cells/cells.py#L2362
  
When I try to run the demo frontend, it repeatedly throws an exception about this being an improper use of string format. I'm not sure why this wasn't caught in any of the tests either:

```
[2019-10-23 15:27:03,471]    ERROR                       cells.py: 483 | 100000003 | Node <obj
ect_database.web.cells.cells.Clickable object at 0x7f56d878ddd8> had exception during recalcul
ation:                                                                                       
Traceback (most recent call last):
  File "/home/ecgade/projects/braxton/10-23/object_database/object_database/web/cells/cells.py
", line 454, in _recalculateCells                                                            
    node.recalculate()
  File "/home/ecgade/projects/braxton/10-23/object_database/object_database/web/cells/cells.py
", line 2371, in recalculate                                                                 
    self.exportData["events"] = {"onclick": self.calculatedOnClick()}
  File "/home/ecgade/projects/braxton/10-23/object_database/object_database/web/cells/cells.py
", line 2361, in calculatedOnClick                                                           
    "cellSocket.sendString(JSON.stringify("
ValueError: Invalid format specifier
```

**Comment by atzannes** [comment]
@darth-cheney  ah, that's my bad (not black's). It should be:
```
 f"{{'event':'click', 'target_cell': '{self.identity}'}}"
```
I made some manual changes because black is not always able to reduce the line length to the desired length, so I had to do some manually.

I'll quickly fix this, but we may want to increase our test coverage of cells.py, which is currently at 60% https://codecov.io/gh/APrioriInvestments/object_database/src/dev/object_database/web/cells/cells.py

(I checked and that line we're talking about is not under test)

**Comment by darth-cheney** [comment]
@atzannes Yeah agreed. I'm adding tests as I go through and do some of these refactorings. Another thing is that the line in question shouldn't even exist: we need to remove all JS calls from the Python side. I'll open an issue for that.

**Comment by atzannes** [comment]
:+1: 
@darth-cheney let me know if you encounter any other broken things, or if my fix didn't fix the problem

**Pull request merged**
